=== corovcam/NPRG036-T2G4/3/xml/schemas/schema-4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="https://www.w3.org/2009/01/xml.xsd"/>
    <xs:element name="name" type="xs:string"/>
    <xs:element name="ISBN" type="xs:string"/>
    <xs:element name="keywords" type="xs:string"/>
    <xs:element name="familyName" type="xs:string"/>
    <xs:element name="givenName" type="xs:string"/>
    <xs:element name="birthDate" type="xs:date"/>
    <xs:element name="emailAdress" type="xs:string"/>
    <xs:element name="description" type="xs:string"/>
    <xs:element name="tag" type="xs:string"/>
    <xs:element name="url" type="xs:anyURI"/>
    <xs:element name="availabilityStarts" type="xs:date"/>
    <xs:element name="availabilityEnds" type="xs:date"/>
    <xs:simpleType name="available">
        <xs:restriction base="xs:string">
            <xs:enumeration value="InStock"/>
            <xs:enumeration value="OutOfStock"/>
            <xs:enumeration value="OnlineOnly"/>
            <xs:enumeration value="LimitedAvailability"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="sku" type="xs:string"/>
    <xs:attribute name="id" type="xs:string"/>
    
    <xs:element name="people">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="person" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="person">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="familyName"/>
                <xs:element ref="givenName" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element ref="birthDate"/>
                <xs:element ref="emailAdress" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="language" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element ref="book" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="xml:lang"/>
            <xs:attribute ref="id"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="book">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ISBN"/>
                <xs:element ref="name"/>
                <xs:element ref="keywords" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="book" minOccurs="0" maxOccurs="unbounded"/>  
                <xs:element ref="language"/> 
                <xs:element ref="inGenre" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element ref="itemOffered" minOccurs="0" maxOccurs="unbounded"/>            
            </xs:sequence>
            <xs:attribute ref="xml:lang"/>
            <xs:attribute ref="id"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="language">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name"/>
                <xs:element ref="description"/>
                <xs:element ref="tag"/>
            </xs:sequence>
            <xs:attribute ref="xml:lang"/>
            <xs:attribute ref="id"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="inGenre">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name"/>
                <xs:element ref="description"/>
            </xs:sequence>
            <xs:attribute ref="xml:lang"/>
            <xs:attribute ref="id"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="itemOffered">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="sku"/>
                <xs:element ref="availabilityStarts"/>
                <xs:element ref="availabilityEnds"/>
                <xs:element name="availability" type="available"/>
                <xs:element ref="makesOffer"/>
            </xs:sequence>
            <xs:attribute ref="id"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="makesOffer">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name"/>
                <xs:element ref="url"/>
                <xs:element ref="emailAdress" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="xml:lang"/>
            <xs:attribute ref="id"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== corovcam/NPRG036-T2G4/3/xml/data/data-4.xml
<?xml version="1.0" encoding="utf-8"?>
<people xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/schema-4.xsd">
    <person xml:lang="en" id="0a206b9f-ac39-4136-8171-1e8b06e3b3f5">
        <familyName>Tolkien</familyName>
        <givenName>John</givenName>
        <givenName>Ronald</givenName>
        <givenName>Reuel</givenName>
        <birthDate>1892-01-03</birthDate>
        <language xml:lang="en" id="en">
            <name>English</name>
            <description>English is a West Germanic language of the Indo-European language family.</description>
            <tag>en</tag>
        </language>

        <book xml:lang="en">
            <ISBN>9780345339706</ISBN>
            <name>The Fellowship of the Ring (The Lord of the Rings, Part 1)</name>
            <keywords>middle-earth</keywords>
            <keywords>quest</keywords>
            <language xml:lang="en">
                <name>English</name>
                <description>English is a West Germanic language of the Indo-European language family.</description>
                <tag>en</tag>
            </language>
            <inGenre xml:lang="en">
                <name>Fantasy</name>
                <description>Fantasy is a genre of speculative fiction involving magical elements, typically set in a fictional universe and sometimes inspired by mythology and folklore.</description>
            </inGenre>
            <itemOffered>
                <sku>KS944RUR</sku>
                <availabilityStarts>2022-09-13</availabilityStarts>
                <availabilityEnds>2032-09-13</availabilityEnds>
                <availability>InStock</availability>
                <makesOffer xml:lang="cs">
                    <name>Krajská knihovna v Pardubicích</name>
                    <url>https://kkpce.cz</url>
                    <emailAdress>dotazy@kkpce.cz</emailAdress>
                </makesOffer>
            </itemOffered>
            <itemOffered>
                <sku>KS945RUR</sku>
                <availabilityStarts>2020-05-01</availabilityStarts>
                <availabilityEnds>2030-09-01</availabilityEnds>
                <availability>InStock</availability>
                <makesOffer xml:lang="cs">
                    <name>Krajská knihovna v Pardubicích</name>
                    <url>https://kkpce.cz</url>
                    <emailAdress>dotazy@kkpce.cz</emailAdress>
                </makesOffer>
            </itemOffered>
            <itemOffered>
                <sku>KS94HRDC</sku>
                <availabilityStarts>2015-05-01</availabilityStarts>
                <availabilityEnds>2025-09-01</availabilityEnds>
                <availability>InStock</availability>
                <makesOffer xml:lang="cs">
                    <name>Knihovna města Hradce Králové</name>
                    <url>https://www.knihovnahk.cz</url>
                    <emailAdress>knihovna@knihovnahk.cz</emailAdress>
                </makesOffer>
            </itemOffered>
        </book>

        <book xml:lang="cs">
            <ISBN>9788072038299</ISBN>
            <name>Společenstvo prstenu</name>
            <keywords>middle-earth</keywords>
            <keywords>quest</keywords>
            <book>
                <ISBN>9780345339706</ISBN>
                <name>The Fellowship of the Ring (The Lord of the Rings, Part 1)</name>
                <keywords>middle-earth</keywords>
                <keywords>quest</keywords>
                <language xml:lang="en">
                    <name>English</name>
                    <description>English is a West Germanic language of the Indo-European language family.</description>
                    <tag>en</tag>
                </language>
                <inGenre xml:lang="en">
                    <name>Fantasy</name>
                    <description>Fantasy is a genre of speculative fiction involving magical elements, typically set in a fictional universe and sometimes inspired by mythology and folklore.</description>
                </inGenre>
            </book>
            <language xml:lang="en">
                <name>Czech</name>
                <description>Spoken by over 10 million people, it serves as the official language of the Czech Republic.</description>
                <tag>cs</tag>
            </language>            
            <inGenre xml:lang="en">
                <name>Fantasy</name>
                <description>Fantasy is a genre of speculative fiction involving magical elements, typically set in a fictional universe and sometimes inspired by mythology and folklore.</description>
            </inGenre>
        </book>
    </person>

    <person xml:lang="en" id="5i824hb6-5839-4563-8271-1e86zwe3b3f6">
        <familyName>Carnegie</familyName>
        <givenName>Dale</givenName>
        <givenName>Brackenridge</givenName>
        <birthDate>1888-11-24</birthDate>
        <language xml:lang="en" id="en">
            <name>English</name>
            <description>English is a West Germanic language of the Indo-European language family.</description>
            <tag>en</tag>
        </language>

        <book xml:lang="en">
            <ISBN>9781785042409</ISBN>
            <name>How to Win Friends and Influence People</name>
            <keywords>communication</keywords>
            <keywords>speaking</keywords>
            <language xml:lang="en">
                <name>English</name>
                <description>English is a West Germanic language of the Indo-European language family.</description>
                <tag>en</tag>
            </language>
            <inGenre xml:lang="en">
                <name>Nonfiction</name>
                <description>Nonfiction is any document or media content that attempts to provide accurate information regarding a real-world topic. It is written to communicate facts or opinions about reality.</description>
            </inGenre>
        </book>

        <book xml:lang="en">
            <ISBN>9788073065195</ISBN>
            <name>Jak získávat přátele a působit na lidi</name>
            <keywords>communication</keywords>
            <keywords>speaking</keywords>
            <book xml:lang="en">
                <ISBN>9781785042409</ISBN>
                <name>How to Win Friends and Influence People</name>
                <keywords>communication</keywords>
                <keywords>speaking</keywords>
                <language xml:lang="en">
                    <name>English</name>
                    <description>English is a West Germanic language of the Indo-European language family.</description>
                    <tag>en</tag>
                </language>
                <inGenre xml:lang="en">
                    <name>Nonfiction</name>
                    <description>Nonfiction is any document or media content that attempts to provide accurate information regarding a real-world topic. It is written to communicate facts or opinions about reality.</description>
                </inGenre>
            </book>
            <language xml:lang="en">
                <name>Czech</name>
                <description>Spoken by over 10 million people, it serves as the official language of the Czech Republic.</description>
                <tag>cs</tag>
            </language>
            <inGenre xml:lang="en">
                <name>Nonfiction</name>
                <description>Nonfiction is any document or media content that attempts to provide accurate information regarding a real-world topic. It is written to communicate facts or opinions about reality.</description>
            </inGenre>
        </book>
    </person>

    <person xml:lang="en" id="06daw835-98sd-4dgf-69a8-sdfe59ed3b3f7">
        <familyName>Huxley</familyName>
        <givenName>Aldous</givenName>
        <givenName>Leonard</givenName>
        <birthDate>1894-07-26</birthDate>
        <language xml:lang="en" id="en">
            <name>English</name>
            <description>English is a West Germanic language of the Indo-European language family.</description>
            <tag>en</tag>
        </language>

        <book xml:lang="en">
            <ISBN>9780099518471</ISBN>
            <name>Brave New World</name>
            <keywords>society</keywords>
            <keywords>future</keywords>
            <keywords>dystopia</keywords>
            <language xml:lang="en">
                <name>English</name>
                <description>English is a West Germanic language of the Indo-European language family.</description>
                <tag>en</tag>
            </language>
            <inGenre xml:lang="en">
                <name>Sci-Fi</name>
                <description>Science fiction (sci-fi) is a form of fiction that deals principally with the impact of actual or imagined science upon society or individuals.</description>
            </inGenre>
        </book>

        <book xml:lang="en">
            <ISBN>9788080618643</ISBN>
            <name>Prekrásny nový svet</name>
            <keywords>society</keywords>
            <keywords>future</keywords>
            <keywords>dystopia</keywords>
            <book xml:lang="en">
                <ISBN>9780099518471</ISBN>
                <name>Brave New World</name>
                <keywords>society</keywords>
                <keywords>future</keywords>
                <keywords>dystopia</keywords>
                <language xml:lang="en">
                    <name>English</name>
                    <description>English is a West Germanic language of the Indo-European language family.</description>
                    <tag>en</tag>
                </language>
                <inGenre xml:lang="en">
                    <name>Sci-Fi</name>
                    <description>Science fiction (sci-fi) is a form of fiction that deals principally with the impact of actual or imagined science upon society or individuals.</description>
                </inGenre>
            </book>
